# -*- coding: utf-8 -*-
"""TextRank.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mtQEO_HR4U6Q7B1nVGKDo1tic_SwvzMj
"""

from nltk.corpus import stopwords
from nltk.cluster.util import cosine_distance
import numpy as np
import networkx as nx

def read_file(file_name):
#     file = open (file_name,"r")
#     filedata = file.readlines()
    filedata = file_name
    article = filedata[0].split(". ")
    #print (article)             # list of all sentences in text

    sentences=[]
    for sentence in article:
        sentence = sentence.replace('"','')   #removing double quotes in text
        sentences.append(sentence.replace("[^a-zA-Z"," ").split(" "))  # removing non characters
    #print (sentences)
    return sentences

def sentence_similarity(s1, s2, stopwords=[]):
    s1 = [w.lower() for w in s1]
    s2 = [w.lower() for w in s2]

    all_words = list(set(s1+s2))
    m=len(all_words)

    v1=[0]*m
    v2=[0]*m

    for w in s1:
        if w in stopwords: continue
        v1[all_words.index(w)]+=1

    for w in s2:
        if w in stopwords: continue
        v2[all_words.index(w)]+=1

    return 1-cosine_distance(v1,v2)

def similarity_matrix(sentences, stop_words):
    n=len(sentences)
    s_m = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            if i==j: continue
            s_m[i][j]=sentence_similarity(sentences[i], sentences[j], stop_words)

    return s_m

import nltk
nltk.download('stopwords')

def summarize(file_name, top_n=3):
    stop_words=stopwords.words('english')
    res=[]
    sentences = read_file(file_name)
    #print (sentences)

    s_m = similarity_matrix(sentences, stop_words)
    s_g = nx.from_numpy_array(s_m)
    scores = nx.pagerank(s_g)

    ranked_sentences = sorted(((scores[i],i,s) for i,s in enumerate(sentences)),reverse=True)
    top_ranked = ranked_sentences[:top_n]
    top_ranked.sort(key = lambda x:x[1])
    print (top_ranked)

    for i in range(top_n):
        res.append(" ".join(top_ranked[i][2]))

    print ("Summary : \n", ". ".join(res))

summarize("enter text here")

